# Generated by Django 3.2.7 on 2021-09-10 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jwt_auth', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_image',
            field=models.CharField(default='https://i.imgur.com/44CkP8U.png', max_length=300),
        ),
    ]
