# Generated by Django 3.2.7 on 2021-09-10 08:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mood',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice', models.CharField(choices=[('Calm', 'Calm'), ('Playful', 'Playful'), ('Adventurous', 'Adventurous')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=100)),
                ('mood', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moods', to='images.mood')),
            ],
        ),
    ]
