# Generated by Django 3.2.7 on 2021-09-09 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mood',
            name='choice',
            field=models.CharField(choices=[('Calm', 'Calm'), ('Playful', 'Playful'), ('Adventurous', 'Adveturous')], max_length=20),
        ),
    ]
