# Generated by Django 3.2.7 on 2021-09-09 11:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0002_alter_mood_choice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='mood',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moods', to='images.mood'),
        ),
        migrations.AlterField(
            model_name='mood',
            name='choice',
            field=models.CharField(choices=[('Calm', 'Calm'), ('Playful', 'Playful'), ('Adventurous', 'Adventurous')], max_length=20),
        ),
    ]
