# Generated by Django 3.2.7 on 2021-09-10 16:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('images', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='liked_by',
            field=models.ManyToManyField(related_name='liked_images', to=settings.AUTH_USER_MODEL),
        ),
    ]
