# Generated by Django 3.2.7 on 2021-09-11 14:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('images', '0003_image_liked_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='orientation',
            field=models.CharField(choices=[('Portrait', 'Portrait'), ('Landscape', 'Landscape')], default=str, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='image',
            name='liked_by',
            field=models.ManyToManyField(blank=True, related_name='liked_images', to=settings.AUTH_USER_MODEL),
        ),
    ]
